### ISSUE TITLE
 DCT scaled block size 0x0 not supported

### ISSUE THREAD

**Issue by wjyspace** [daniellerch/hstego#1]
when i use python command `hstego.py embed secret.txt cover.jpg stego2.jpg MyP4ssw0rd101`  i get error
Error: DCT scaled block size 0x0 not supported
Error writing to file: stego2.jpg

**Comment by daniellerch** [comment]
Can you provide the image you are using?
Thanks.

**Comment by daniellerch** [comment]
Detected and fixed.
